### ISSUE TITLE
Crete generic order By

### ISSUE THREAD

**Issue by adblancod** [gon250/ng2-orderBy-pipe#10]
The idea is to create a pipe which will work with the key word 'orderBy'. That pipe will detect the type of array will order it automatically (independently if it is a simple or complex array)

**Comment by gon250** [comment]
@adblancod  I have added this [helper-pipe](https://github.com/gon250/ng2-orderBy-pipe/blob/master/src/utils/helper-pipe.ts) so you can reuse all the functions for the generic pipe. I also have added an example so you can see how include the functions.
